services:
  api:
    build:
      context: ../
    container_name: task-manager-api
    command: ./infra/commands/api.sh
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - task-manager-back-tier

  db:
    image: postgres:17.5
    container_name: task-manager-db
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-manager-back-tier


volumes:
  postgres_data:

networks:
  task-manager-back-tier: